'use strict';
const $=id=>document.getElementById(id);let selected=null,recipes=[];
const el=(tag,text,cls)=>{const n=document.createElement(tag);if(text!=null)n.textContent=text;if(cls)n.className=cls;return n};
async function api(path,body){const r=await fetch('/api/'+path,body?{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}:{});const j=await r.json();if(!r.ok)throw Error(j.error||'Request failed');return j}
function notice(message,error=false){$('notice').className=error?'error':'success';$('notice').textContent=message}
function safeLink(url,text){const a=el('a',text);try{const u=new URL(url);if(['http:','https:'].includes(u.protocol)){a.href=u.href;a.target='_blank';a.rel='noopener noreferrer'}}catch{}return a}
async function loadRecipes(){recipes=await api('recipes');$('recipe').replaceChildren(new Option('General extraction',''));for(const r of recipes)$('recipe').add(new Option(r.name,r.name))}
async function detail(id){selected=id;const [s,rows]=await Promise.all([api('jobs/'+id),api('jobs/'+id+'/results')]);const d=$('detail');d.hidden=false;d.replaceChildren(el('h2','Run '+id),el('p',s.state+' · '+(s.counts.done||0)+' extracted · '+(s.counts.failed||0)+' failed · '+s.bytes.toLocaleString()+' transferred bytes'));const links=el('div',null,'exports');for(const format of ['json','csv']){const a=el('a','Download '+format.toUpperCase());a.href='/api/jobs/'+id+'/export?format='+format;links.append(a)}d.append(links);if(['queued','running'].includes(s.state)){const c=el('button','Cancel run','secondary');c.onclick=async()=>{await api('jobs/'+id+'/cancel',{});await refresh()};d.append(c)}d.append(el('pre',s.events.map(e=>new Date(e.ts*1000).toLocaleTimeString()+'  '+e.message).join('\n')));for(const row of rows){const block=el('div',null,'result');block.append(safeLink(row.url,row.result?.title||row.url));if(row.error)block.append(el('p',row.error.code+': '+row.error.message,'error'));if(row.result){const r=row.result;block.append(el('p',r.text.slice(0,1200)));if(Object.keys(r.data||{}).length)block.append(el('pre',JSON.stringify({data:r.data,evidence:r.evidence,validation_errors:r.validation_errors},null,2)));block.append(el('small',(r.rendered?'Rendered':'HTML')+' · '+r.elapsed_ms+' ms · source '+r.source_sha256.slice(0,16)))}d.append(block)}}
async function refresh(){try{const [h,jobs]=await Promise.all([api('health'),api('jobs')]);$('health').textContent=h.worker_alive?'Engine online':'Engine ready · starts with your next run';$('jobs').replaceChildren();if(!jobs.length)$('jobs').append(el('p','Your first run will appear here.','muted'));for(const id of ['before','after']){const old=$(id).value;$(id).replaceChildren();for(const j of jobs)$(id).add(new Option(j.id+' · '+j.state,j.id));if(old)$(id).value=old}for(const j of jobs){const card=el('div',null,'job'),left=el('div');left.append(el('strong',j.request.urls[0]),el('small',j.id+' · '+(j.counts.done||0)+' / '+j.total+' pages · '+new Date(j.created*1000).toLocaleString()));const state=el('span',j.state,'state'),button=el('button','View','secondary');button.onclick=()=>detail(j.id).catch(e=>notice(e.message,true));card.append(left,state,button);$('jobs').append(card)}if(selected)await detail(selected)}catch(e){notice('Connection unavailable: '+e.message,true)}}
$('crawl').onsubmit=async e=>{e.preventDefault();const button=e.submitter;button.disabled=true;try{const recipe=recipes.find(r=>r.name===$('recipe').value)?.recipe;const job=await api('jobs',{urls:$('urls').value.trim().split(/\s+/),max_pages:Number($('pages').value),max_depth:Number($('depth').value),render:$('render').value,cache:!$('fresh').checked,...(recipe?{recipe}:{})});notice('Run saved. You can leave this page; collection continues.');selected=job.id;await refresh();$('runs').scrollIntoView({behavior:'smooth'})}catch(error){notice(error.message,true)}finally{button.disabled=false}};
$('recipe-form').onsubmit=async e=>{e.preventDefault();try{await api('recipes',{name:$('recipe-name').value,recipe:JSON.parse($('recipe-json').value)});await loadRecipes();notice('Recipe saved.')}catch(error){notice(error.message,true)}};
$('search-form').onsubmit=async e=>{e.preventDefault();try{const rows=await api('search?q='+encodeURIComponent($('query').value));$('search-results').replaceChildren();for(const r of rows){const div=el('div',null,'result');div.append(safeLink(r.url,r.title||r.url),el('p',r.excerpt));$('search-results').append(div)}if(!rows.length)$('search-results').append(el('p','No saved results match.','muted'))}catch(error){notice(error.message,true)}};
$('compare-form').onsubmit=async e=>{e.preventDefault();try{$('diff').textContent=JSON.stringify(await api('compare?before='+encodeURIComponent($('before').value)+'&after='+encodeURIComponent($('after').value)),null,2)}catch(error){notice(error.message,true)}};
$('refresh').onclick=refresh;loadRecipes().catch(e=>notice(e.message,true));refresh();setInterval(()=>{if(!document.hidden)refresh()},3000);
